version: '3.7'
services:
  #Nginx Service
 
  girafo:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    networks:
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=girafo"
      - "traefik.frontend.rule=Host:girafo.localhost"
      - "traefik.port=80"    
    volumes:
      - ./indexG1.html:/usr/share/nginx/html/index.html
    
#Docker Networks
networks:
  traefik:
    external: 
      name: traefik_webgateway